version: '3'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo-3-bai-toan
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always